language: php

php:
    - 5.4
    - 5.5
    - 5.6
    - hhvm

install:
    - composer require satooshi/php-coveralls

before_script: 
    - mkdir -p build/logs

script:
    - php vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_script:
    - php vendor/bin/coveralls
