language: php

php:
    - 5.4
    - 5.5
    - 5.6
    - hhvm
    - nightly

install:
    - composer require satooshi/php-coveralls

before_script: 
    - mkdir -p build/logs

script: 
    - vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_success:
    - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then php vendor/bin/coveralls -v; fi;'